name: Snapshot Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Latest Snapshot Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build Native Image Linux
        run: mvn -B package -DskipTests -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true --file backend/pom.xml

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: |
            backend/target/*-runner


  build-windows:
    name: Build Latest Snapshot Windows
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image Windows
        run: |
          mvn -B package -DskipTests -Dnative --file backend/pom.xml

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts-windows
          path: |
            backend/target/*-runner.exe


  build-frontend:
    name: Build Latest Snapshot Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

 # placeholder for build arg, will be replaced with proper backend once its up
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          echo "VITE_API_URL=https://localhost:8443" > .env.production
          npm run build

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts-frontend
          path: |
            frontend/dist/**/*


      

  release:
    name: Create Latest Snapshot Release
    needs: [build, build-windows, build-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Get Build Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts


      - name: Generate Example JWT Keys and Self-Signed SSL Certs
        run: |
          mkdir -p backend/release-assets
          mkdir -p backend/release-assets/keys backend/release-assets/certs
          cp backend/generate-keys.sh backend/release-assets/generate-keys.sh
          chmod +x backend/release-assets/generate-keys.sh
          cd backend/release-assets
          bash ./generate-keys.sh
          cd ../../

      

      - name: Prepare Release Bundle
        run: |
          mkdir -p release-dist/keys release-dist/certs
          mkdir -p release-dist-windows/keys release-dist-windows/certs
          cp artifacts/build-artifacts/* release-dist/
          cp backend/src/main/resources/application.yml release-dist/application.yml.example
          cp backend/src/main/resources/application.yml release-dist-windows/application.yml.example
          cp backend/release-assets/keys/* release-dist/keys/
          cp backend/release-assets/certs/* release-dist/certs/
          cp backend/release-assets/keys/* release-dist-windows/keys/
          cp backend/release-assets/certs/* release-dist-windows/certs/
          cp backend/release-assets/generate-keys.sh release-dist/
          cp backend/generate-keys.ps1 release-dist-windows/
          tar -zcvf resonant-backend-snapshot.tar.gz release-dist/
          cp artifacts/build-artifacts-windows/* release-dist-windows/
          zip -r resonant-backend-snapshot.zip release-dist-windows/
          zip -r resonant-backend-snapshot-frontend.zip artifacts/build-artifacts-frontend/*

      - name: Delete Existing Snapshot Release
        run: gh release delete experimental --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Latest Snapshot Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "experimental"
          prerelease: false
          name: "Latest Snapshot Build"
          body: "Latest change: ${{ github.event.head_commit.message }} (${{
            github.event.head_commit.id }})"
          files: |
            resonant-backend-snapshot.tar.gz
            resonant-backend-snapshot.zip
            resonant-backend-snapshot-frontend.zip


      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: artifacts/build-artifacts-frontend/
    
  release-pages:
      needs: release
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.pages-deploy.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: pages-deploy
          uses: actions/deploy-pages@v4

